management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 60000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: password@123
    url: jdbc:mysql://localhost:3306/syeddb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
